let data = [
  {
    EventId: "1",
    titleGeo: "დინამო ბათუმი V დინამო თბილისი (1)",
    titleEng: "Dinamo Batumi V Dinamo Tbilisi (1)",
    titleRus: "Динамо Батуми V Динамо Тбилиси (1)",
    groupName: "sport (1)",
    samallImage: "test.jpg (1)",
    mediumImage: "test.jpg (1)",
    Image: "test.jpg (1)",
    startedAt: "2021-06-25 (1)",
    sellStartedAt: "2021-06-25",
    descriptionGeo: "საქართველოს ჩემპიონატის კალენდარული მატჩი. (1)",
    descriptionEng: "Georgian championship calendar match. (1)",
    descriptionRus: "Матч календаря чемпионата Грузии. (1)",
    location: "Batumi stadium (1)",
    addressGeo: "ბათუმი (1)",
    addressEng: "Batumi (1)",
    addressRus: "Батуми (1)",
    price: "5 - 25 (1)",
    status: "Active (1)",
    top: false,
  },
  {
    EventId: "2",
    titleGeo: "დინამო ბათუმი V დინამო თბილისი (2)",
    titleEng: "Dinamo Batumi V Dinamo Tbilisi (2)",
    titleRus: "Динамо Батуми V Динамо Тбилиси (2)",
    groupName: "sport (2)",
    samallImage: "test.jpg (2)",
    mediumImage: "test.jpg (2)",
    Image: "test.jpg (2)",
    startedAt: "2021-06-25 (2)",
    sellStartedAt: "2021-06-25",
    descriptionGeo: "საქართველოს ჩემპიონატის კალენდარული მატჩი. (2)",
    descriptionEng: "Georgian championship calendar match. (2)",
    descriptionRus: "Матч календаря чемпионата Грузии. (2)",
    location: "Batumi stadium (2)",
    addressGeo: "ბათუმი (2)",
    addressEng: "Batumi (2)",
    addressRus: "Батуми (2)",
    price: "5 - 25 (2)",
    status: "Active (2)",
    top: true,
  },
  {
    EventId: "3",
    titleGeo: "დინამო ბათუმი V დინამო თბილისი (3)",
    titleEng: "Dinamo Batumi V Dinamo Tbilisi (3)",
    titleRus: "Динамо Батуми V Динамо Тбилиси (3)",
    groupName: "sport (3)",
    samallImage: "test.jpg (3)",
    mediumImage: "test.jpg (3)",
    Image: "test.jpg (3)",
    startedAt: "2021-06-25 (3)",
    sellStartedAt: "2021-06-25",
    descriptionGeo: "საქართველოს ჩემპიონატის კალენდარული მატჩი. (3)",
    descriptionEng: "Georgian championship calendar match. (3)",
    descriptionRus: "Матч календаря чемпионата Грузии. (3)",
    location: "Batumi stadium (3)",
    addressGeo: "ბათუმი (3)",
    addressEng: "Batumi (3)",
    addressRus: "Батуми (3)",
    price: "5 - 25 (3)",
    status: "Active (3)",
    top: false,
  },
];

module.exports = data;
